#!/usr/bin/env python3
"""
Interactive script to set up Firebase environment variables.
This script will prompt you for each Firebase config value and save them to frontend/.env
"""

import os
from pathlib import Path

def main():
    print("=" * 60)
    print("Firebase Environment Variables Setup")
    print("=" * 60)
    print()
    print("This script will help you set up your Firebase configuration.")
    print("You can find these values in Firebase Console > Project Settings > Your apps")
    print()
    
    # Path to .env file in frontend directory
    frontend_dir = Path(__file__).parent / "frontend"
    env_file = frontend_dir / ".env"
    
    # Check if .env already exists
    existing_vars = {}
    if env_file.exists():
        print(f"⚠️  Found existing .env file at: {env_file}")
        print("Reading existing values...")
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    existing_vars[key.strip()] = value.strip()
        
        if existing_vars:
            print(f"Found {len(existing_vars)} existing variables.")
            response = input("\nDo you want to update existing values? (y/n): ").strip().lower()
            if response != 'y':
                print("Cancelled. No changes made.")
                return
    
    # Define the Firebase environment variables we need
    firebase_vars = {
        "VITE_FIREBASE_API_KEY": {
            "prompt": "Enter your Firebase API Key",
            "description": "Found in Firebase Console > Project Settings > Your apps > Web app config"
        },
        "VITE_FIREBASE_AUTH_DOMAIN": {
            "prompt": "Enter your Firebase Auth Domain",
            "description": "Usually: your-project-id.firebaseapp.com"
        },
        "VITE_FIREBASE_PROJECT_ID": {
            "prompt": "Enter your Firebase Project ID",
            "description": "Your Firebase project identifier"
        },
        "VITE_FIREBASE_STORAGE_BUCKET": {
            "prompt": "Enter your Firebase Storage Bucket",
            "description": "Usually: your-project-id.appspot.com"
        },
        "VITE_FIREBASE_MESSAGING_SENDER_ID": {
            "prompt": "Enter your Firebase Messaging Sender ID",
            "description": "Numeric ID for Firebase Cloud Messaging"
        },
        "VITE_FIREBASE_APP_ID": {
            "prompt": "Enter your Firebase App ID",
            "description": "Your Firebase web app identifier"
        }
    }
    
    print("\n" + "=" * 60)
    print("Enter your Firebase configuration values:")
    print("=" * 60)
    print()
    
    # Collect values
    values = {}
    for var_name, var_info in firebase_vars.items():
        existing_value = existing_vars.get(var_name, "")
        
        if existing_value:
            print(f"{var_info['prompt']}:")
            print(f"  ({var_info['description']})")
            print(f"  Current value: {existing_value[:50]}{'...' if len(existing_value) > 50 else ''}")
            user_input = input(f"  Enter new value (or press Enter to keep current): ").strip()
            if user_input:
                values[var_name] = user_input
            else:
                values[var_name] = existing_value
        else:
            print(f"{var_info['prompt']}:")
            print(f"  ({var_info['description']})")
            user_input = input(f"  Value: ").strip()
            if user_input:
                values[var_name] = user_input
            else:
                print(f"  ⚠️  Warning: {var_name} is empty!")
                values[var_name] = ""
        
        print()
    
    # Confirm before writing
    print("=" * 60)
    print("Review your configuration:")
    print("=" * 60)
    for var_name, value in values.items():
        display_value = value[:50] + "..." if len(value) > 50 else value
        status = "✓" if value else "⚠️  (empty)"
        print(f"{status} {var_name}: {display_value}")
    
    print()
    confirm = input("Save these values to .env file? (y/n): ").strip().lower()
    
    if confirm != 'y':
        print("Cancelled. No changes made.")
        return
    
    # Ensure frontend directory exists
    frontend_dir.mkdir(exist_ok=True)
    
    # Write to .env file
    try:
        with open(env_file, 'w') as f:
            f.write("# Firebase Configuration\n")
            f.write("# Generated by setup_firebase_env.py\n")
            f.write("# Do not commit this file to version control\n\n")
            
            for var_name, value in values.items():
                f.write(f"{var_name}={value}\n")
        
        print()
        print("✅ Success! Firebase environment variables saved to:")
        print(f"   {env_file}")
        print()
        print("Next steps:")
        print("1. Make sure your .env file is in .gitignore (it should be already)")
        print("2. Restart your frontend dev server if it's running")
        print("3. Test the authentication in your app")
        
    except Exception as e:
        print(f"\n❌ Error writing to .env file: {e}")
        return

if __name__ == "__main__":
    main()
